### ISSUE TITLE
您好，请问这份开源的代码和那个微信Demo使用的代码一样吗？感觉效果没有微信的好。

### ISSUE THREAD

**Issue by Ant0082** [THUDM/XDAI#2]
如果不一样，微信Demo是做了一些其他优化吗？方便透漏吗？

**Comment by tianxinliao** [comment]
你好，请问你可以跑通了吗？我遇到一点问题，你的环境是直接用 requirement.txt 配置的吗？

**Comment by Ant0082** [comment]
> 你好，请问你可以跑通了吗？我遇到一点问题，你的环境是直接用 requirement.txt 配置的吗？

什么问题？

**Comment by tianxinliao** [comment]
> > 你好，请问你可以跑通了吗？我遇到一点问题，你的环境是直接用 requirement.txt 配置的吗？
> 
> 什么问题？

我根据 readme 的指导，直接 pip install -r requirements.txt 有几个包无法安装，会报错

**Comment by zxhhh97** [comment]
感谢您的关注。这份代码是早期的一个简单版本，我们部署在线上的服务有持续的优化，所以可能效果上可能有差异，很抱歉给您带来的不便；
如果想要自行部署，遇到安装包报错，有可能是和预训练语言模型服务相关的包。建议可以先调试部署PLM服务，参考https://github.com/THUDM/GLM 和 https://github.com/THUDM/GLM-130B 中的步骤（尤其是解决cuda环境问题），或者直接替换续写服务api，如使用https://tianqi.aminer.cn/ 的现成接口。

**Comment by Ant0082** [comment]
> 感谢您的关注。这份代码是早期的一个简单版本，我们部署在线上的服务有持续的优化，所以可能效果上可能有差异，很抱歉给您带来的不便； 如果想要自行部署，遇到安装包报错，有可能是和预训练语言模型服务相关的包。建议可以先调试部署PLM服务，参考https://github.com/THUDM/GLM 和 https://github.com/THUDM/GLM-130B 中的步骤（尤其是解决cuda环境问题），或者直接替换续写服务api，如使用https://tianqi.aminer.cn/ 的现成接口。

感谢回复，优化的内容方便透漏吗？或者方向，是只替换了PLM，还是还有其他方向的优化？谢谢

**Comment by zxhhh97** [comment]
> 感谢回复，优化的内容方便透漏吗？或者方向，是只替换了PLM，还是还有其他方向的优化？谢谢

主要需要尝试更多prompt工程的调试，以及根据语言模型返回结果的特点进行后处理，比如去除一些重复的segments。另外外部知识的来源也可以个性化选择和处理。

**Comment by Ant0082** [comment]
> > 感谢回复，优化的内容方便透漏吗？或者方向，是只替换了PLM，还是还有其他方向的优化？谢谢
> 
> 主要需要尝试更多prompt工程的调试，以及根据语言模型返回结果的特点进行后处理，比如去除一些重复的segments。另外外部知识的来源也可以个性化选择和处理。

感谢回复。
